DROP VIEW all_appts;
DROP VIEW item_information;
DROP VIEW medical_staff_contact;
DROP VIEW non_medical_staff_contact;
DROP VIEW patient_contact;
DROP VIEW shipment_decoded;
DROP VIEW staff_availability;
DROP VIEW staff_supplies_usage;
DROP VIEW upcoming_appts;